infnet-bl6-fdaN-tp3/Models/ErrorViewModel.cs
namespace infnet_bl6_fdaN_at.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

infnet-bl6-fdaN-tp3/Models/Pessoa.cs
using System.ComponentModel.DataAnnotations;

namespace infnet_bl6_fdaN_at.Models
{
    public class Pessoa
    {
        #region atributos
        private int _pessoaId;
        private string _nome;
        private string _sobrenome;
        private DateTime _dataNascimento;
        #endregion

        #region propriedades
        public int PessoaId
        {
            get { return _pessoaId; }
            set { _pessoaId = value; }
        }
        [Display(Name = "Nome")]
        public string Nome
        {
            get { return _nome; }
            set { _nome = value; }
        }

        [Display(Name = "Sobrenome")]
        public string Sobrenome
        {
            get { return _sobrenome; }
            set { _sobrenome = value; }
        }

        [Display(Name = "Data de nascimento")]
        [DataType(DataType.Date)]
        public DateTime DataNascimento
        {
            get { return _dataNascimento; }
            set { _dataNascimento = value; }
        }
        [Display(Name = "Nome completo")]
        public string NomeCompleto
        {
            get { return _nome + " " + _sobrenome; }
        }
        [Display(Name = "Próximo aniversário")]
        [DataType(DataType.Date)]
        public DateTime ProximoAniversario
        {
            get { return ProximoAniversarioFuncao(); }
        }
        [Display(Name = "Dias para aniversário")]
        public int DiasFaltantes
        {
            get { return CalculaDiasFaltantesFuncao(); }
        }

        #endregion

        #region métodos
        //public Pessoa() { }

        public DateTime ProximoAniversarioFuncao()
        {
            DateTime dataProximoAniversario = new(DateTime.Now.Year, DataNascimento.Month, DataNascimento.Day, 0, 0, 0);
            if (DateTime.Compare(dataProximoAniversario, DateTime.Today) < 0)
            {
                dataProximoAniversario = dataProximoAniversario.AddYears(1);
            }
            return dataProximoAniversario;
        }
        public int CalculaDiasFaltantesFuncao()
        {
            DateTime dataAtual = new(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day);
            DateTime dataAniversario = ProximoAniversarioFuncao();
            DateTime dataProximoAniversario = dataAniversario;

            if (dataAtual.Month == dataAniversario.Month &&
                dataAtual.Day == dataAniversario.Day)
            {
                return 0;
            }
            int difDatas = (int)dataAtual.Subtract(dataProximoAniversario).TotalDays;
            if (difDatas < 0) { difDatas *= -1; }

            return difDatas;
        }
        public bool NomeCompletoPossui(string nomePesquisa)
        {
            return NomeCompleto.ToLowerInvariant().Contains(nomePesquisa.Trim().ToLowerInvariant());
        }
        #endregion
    }
}

infnet-bl6-fdaN-tp3/Controllers/PessoasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using infnet_bl6_fdaN_at.Data;
using infnet_bl6_fdaN_at.Models;

namespace infnet_bl6_fdaN_at.Controllers
{
    public class PessoasController : Controller
    {
        private readonly infnet_bl6_fdaN_atContext _context;

        public PessoasController(infnet_bl6_fdaN_atContext context)
        {
            _context = context;
        }

        // GET: Pessoas
        public async Task<IActionResult> Index(string nomePesquisa)
        {
            var pessoas = await _context.Pessoa.ToListAsync();

            if (!string.IsNullOrEmpty(nomePesquisa))
            {
                pessoas = pessoas.Where(pessoa => pessoa.NomeCompletoPossui(nomePesquisa)).ToList();
            }
            pessoas.Sort(delegate (Pessoa x, Pessoa y)
            {
                return x.DiasFaltantes.CompareTo(y.DiasFaltantes);
            });

            return View(pessoas);
        }

        // GET: Pessoas/Details/5
        public async Task<IActionResult> Exibir(int? id)
        {
            if (id == null || _context.Pessoa == null)
            {
                return NotFound();
            }

            var pessoa = await _context.Pessoa
                .FirstOrDefaultAsync(m => m.PessoaId == id);
            if (pessoa == null)
            {
                return NotFound();
            }

            return View(pessoa);
        }

        // GET: Pessoas/Create
        public IActionResult Incluir()
        {
            return View();
        }

        // POST: Pessoas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Incluir([Bind("PessoaId,Nome,Sobrenome,DataNascimento")] Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pessoa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pessoa);
        }

        // GET: Pessoas/Edit/5
        public async Task<IActionResult> Alterar(int? id)
        {
            if (id == null || _context.Pessoa == null)
            {
                return NotFound();
            }

            var pessoa = await _context.Pessoa.FindAsync(id);
            if (pessoa == null)
            {
                return NotFound();
            }
            return View(pessoa);
        }

        // POST: Pessoas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Alterar(int id, [Bind("PessoaId,Nome,Sobrenome,DataNascimento")] Pessoa pessoa)
        {
            if (id != pessoa.PessoaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pessoa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExistePessoa(pessoa.PessoaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pessoa);
        }

        // GET: Pessoas/Delete/5
        public async Task<IActionResult> Excluir(int? id)
        {
            if (id == null || _context.Pessoa == null)
            {
                return NotFound();
            }

            var pessoa = await _context.Pessoa
                .FirstOrDefaultAsync(m => m.PessoaId == id);
            if (pessoa == null)
            {
                return NotFound();
            }

            return View(pessoa);
        }

        // POST: Pessoas/Delete/5
        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmarExcluir(int id)
        {
            if (_context.Pessoa == null)
            {
                return Problem("Entity set 'infnet_bl6_fdaN_atContext.Pessoa'  is null.");
            }
            var pessoa = await _context.Pessoa.FindAsync(id);
            if (pessoa != null)
            {
                _context.Pessoa.Remove(pessoa);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExistePessoa(int id)
        {
            return _context.Pessoa.Any(e => e.PessoaId == id);
        }
    }
}

infnet-bl6-fdaN-tp3/Views/Pessoas/Alterar.cshtml
@model infnet_bl6_fdaN_at.Models.Pessoa

@{
    ViewData["Title"] = "Alterar";
}

<h1>Alterar</h1>

<h4>Pessoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Alterar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PessoaId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Alterar" class="btn btn-primary" /> |
                <a asp-action="Index">Voltar para a lista</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

infnet-bl6-fdaN-tp3/Views/Pessoas/Excluir.cshtml
@model infnet_bl6_fdaN_at.Models.Pessoa

@{
    ViewData["Title"] = "Excluir";
}

<h1>Excluir</h1>

<h3>Tem certeza de que quer excluir esta pessoa?</h3>
<div>
    <h4>Pessoa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>
    </dl>
    
    <form asp-action="Excluir">
        <br />
        <input type="hidden" asp-for="PessoaId" />
        <input type="submit" value="Ecluir" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar para a lista</a>
    </form>
</div>

infnet-bl6-fdaN-tp3/Views/Pessoas/Exibir.cshtml
@model infnet_bl6_fdaN_at.Models.Pessoa

@{
    ViewData["Title"] = "Exibir";
}

<h1>Exibir</h1>

<div>
    <h4>Pessoa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeCompleto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeCompleto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProximoAniversario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProximoAniversario)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DiasFaltantes)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DiasFaltantes)
        </dd>
    </dl>
</div>
<div>
    <br />
    <a asp-action="Alterar" asp-route-id="@Model?.PessoaId">Alterar</a> |
    <a asp-action="Index">Voltar para a lista</a>
</div>

infnet-bl6-fdaN-tp3/Views/Pessoas/Incluir.cshtml
@model infnet_bl6_fdaN_at.Models.Pessoa

@{
    ViewData["Title"] = "Incluir";
}

<h1>Incluir</h1>

<h4>Pessoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Incluir">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Incluir" class="btn btn-primary" /> |
                <a asp-action="Index">Voltar para a lista</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

infnet-bl6-fdaN-tp3/Views/Pessoas/Index.cshtml
@model IEnumerable<infnet_bl6_fdaN_at.Models.Pessoa>

@{
    ViewData["Title"] = "Index";
}
<h1>Agenda de aniversários</h1>

<h3>Aniversariantes de hoje: @DateTime.Today.ToString("dd/MM/yyyy")</h3>
<h5>
    <table class="list">
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    @if (item.DiasFaltantes == 0)
                    {
                        <td>- 
                            @Html.DisplayFor(modelItem => item.NomeCompleto)
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</h5>
<br />
<br />

<h3>Cadastro de pessoas</h3>

<p>
    <a asp-action="Incluir">Incluir</a>
</p>
@using (Html.BeginForm())
{
    <p>
        Encontrar pessoa: @Html.TextBox("nomePesquisa")
        <input type="submit" value="Pesquisar" />
    </p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomeCompleto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataNascimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProximoAniversario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DiasFaltantes)
            </th>
            <th>Açoes</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeCompleto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataNascimento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProximoAniversario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DiasFaltantes)
                </td>
                <td>
                    <a asp-action="Alterar" asp-route-id="@item.PessoaId">Alterar</a> |
                    <a asp-action="Exibir" asp-route-id="@item.PessoaId">Exibir</a> |
                    <a asp-action="Excluir" asp-route-id="@item.PessoaId">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

infnet-bl6-fdaN-tp3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - infnet_bl6_fdaN_at</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/infnet_bl6_fdaN_at.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">infnet_bl6_fdaN_at</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoas" asp-action="Index">Pessoas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - infnet_bl6_fdaN_at - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>